"""`compare` two result files, and render a result into docs/performance-baselines.md."""
from __future__ import annotations

MiB = 2 ** 20
# Lists and descriptive strings are not metrics; `runs` is inside a timed metric.
SKIP = {"env", "sample", "slowest", "mismatch_details", "has_error_files", "runs", "roots",
        "invalid_utf8_files", "has_error_disagreements", "warnings"}


def is_timed(v):
    return isinstance(v, dict) and {"median", "min", "max"} <= set(v)


def flatten(result, prefix=""):
    """{dotted path: timed dict | number} over every metric of a result file."""
    out = {}
    for k, v in (result.items() if isinstance(result, dict) else ()):
        if k in SKIP:
            continue
        path = f"{prefix}{k}"
        if is_timed(v):
            out[path] = v
        elif isinstance(v, dict):
            out |= flatten(v, path + ".")
        elif isinstance(v, (int, float)) and not isinstance(v, bool):
            out[path] = v
    return out


def compare(old, new):
    """-> lines: one per metric present in either file. `!` = the median moved by more than
    the measured spread (max - min) of either run; `?` = a changed value that has no measured
    spread (a single measurement or a derived figure); `+`/`-` = only in the new/old file."""
    a, b = flatten(old.get("groups", old)), flatten(new.get("groups", new))
    lines = [f"{'metric':<70} {'old':>14} {'new':>14} {'delta':>14} {'rel':>9}  flag"]
    for path in sorted(set(a) | set(b)):
        if path not in a or path not in b:
            lines.append(f"{path:<70} {'-' if path not in a else _num(a[path]):>14} "
                         f"{'-' if path not in b else _num(b[path]):>14} {'':>14} {'':>9}  "
                         + ("+" if path not in a else "-"))
            continue
        x, y = a[path], b[path]
        xv, yv = (x["median"], y["median"]) if is_timed(x) and is_timed(y) else (_val(x), _val(y))
        delta = yv - xv
        rel = f"{delta / xv * 100:+.2f}%" if xv else ("+0.00%" if not delta else "n/a")
        if is_timed(x) and is_timed(y):
            flag = "!" if abs(delta) > max(x["max"] - x["min"], y["max"] - y["min"]) else ""
        else:
            flag = "?" if delta else ""
        lines.append(f"{path:<70} {_num(xv):>14} {_num(yv):>14} {_num(delta):>14} {rel:>9}  {flag}")
    envs = old.get("env", {}), new.get("env", {})
    for k in sorted(set(envs[0]) | set(envs[1])):
        if k not in ("load_at_start", "load_at_end") and envs[0].get(k) != envs[1].get(k):
            lines.append(f"env {k}: {envs[0].get(k)!r} -> {envs[1].get(k)!r}")
    return lines


def _val(v):
    return v["median"] if is_timed(v) else v


def _num(v):
    v = _val(v)
    return f"{v:.4g}" if isinstance(v, float) else str(v)


# ---- markdown -------------------------------------------------------------------------

def _t(v, fmt="{:.1f}"):
    return f"{fmt.format(v['median'])} ({fmt.format(v['min'])}-{fmt.format(v['max'])})"


def _mib(n):
    return f"{n / MiB:,.1f} MiB"


def render(r, json_rel):
    g, env = r["groups"], r["env"]
    L = ["# Performance baselines", "",
         f"Generated by `python -m tools.perf render {json_rel}` from **`{json_rel}`**, the committed "
         "result of the run below. Do not edit the numbers by hand: re-measure, or re-render.", "",
         f"- recorded: {r['started']} to {r['finished']}",
         f"- command: `{r['command']}`", ""]
    if r.get("warnings"):
        L += ["**Warnings raised during this run:**", "", *(f"- {w}" for w in r["warnings"]), ""]
    L += ["## Environment", "", "| | |", "|---|---|"]
    for k in ("cpu", "cores_logical", "cores_physical", "os", "python", "py_tree_sitter", "psutil",
              "tree_sitter_cli", "node", "web_tree_sitter", "grammar_sha", "repo_head"):
        L.append(f"| {k} | `{env[k]}` |")
    L.append(f"| RAM | {_mib(env['ram_bytes'])} |")
    for label, c in env["corpora"].items():
        L.append(f"| corpus {label} | `{c['root']}` at `{c['head']}` |")
    for when in ("load_at_start", "load_at_end"):
        if when in env:
            ld = env[when]
            L.append(f"| {when.replace('_', ' ')} | CPU {ld['cpu_percent_2s']}% over 2 s, "
                     f"{_mib(ld['ram_available_bytes'])} RAM free{' -- BUSY' if ld['busy'] else ''} |")
    L += ["", "`grammar_sha` is the oracle's hash (first 16 hex digits of sha256 over grammar.js, "
          "src/scanner.c, src/parser.c and src/**/*.h): the same inputs, so an oracle report and a "
          "perf result with equal hashes measured the same parser.", ""]

    if "native" in g:
        n = g["native"]
        L += ["## Native throughput (py-tree-sitter, in-process)", "",
              f"Files are read into memory first ({n['read_seconds']:.2f} s for all of them, not included "
              f"below). Then one discarded warm-up pass and {n['repeats']} timed passes; each cell is the "
              f"median with the (min-max) over the passes. *Single* times only `parser.parse()`, one file "
              f"at a time in one process. *Parallel* is wall time for {n['workers']} worker processes "
              f"(the oracle's default `--workers`, logical cores - 1) reading the sources from one shared-"
              f"memory block, {n['chunk']} files per task.", "",
              "| corpus | files | size | has_error | single files/s | single MiB/s | parallel files/s | parallel MiB/s |",
              "|---|---:|---:|---:|---:|---:|---:|---:|"]
        for name, c in n["corpora"].items():
            L.append(f"| {name} | {c['files']:,} | {_mib(c['bytes'])} | {c['has_error']} | "
                     f"{_t(c['single']['files_per_s'], '{:,.0f}')} | {_t(c['single']['mib_per_s'], '{:.2f}')} | "
                     f"{_t(c['parallel']['files_per_s'], '{:,.0f}')} | {_t(c['parallel']['mib_per_s'], '{:.1f}')} |")
        L += ["", "Per-file latency, ms (single-threaded; each file's median over the timed passes):", "",
              "| corpus | p50 | p95 | p99 | max | mean |", "|---|---:|---:|---:|---:|---:|"]
        for name, c in n["corpora"].items():
            lt = c["latency_ms"]
            L.append(f"| {name} | {lt['p50']:.2f} | {lt['p95']:.2f} | {lt['p99']:.2f} | {lt['max']:.1f} | {lt['mean']:.2f} |")
        L += ["", "Files with `has_error` (the sanity column; BCApps is known to have 2 visible-error files):", ""]
        L += [f"- `{f}`" for c in list(n["corpora"].values())[:-1] for f in c["has_error_files"]] or ["- none"]
        L += ["", "The 10 slowest files (all corpora):", "", "| file | bytes | ms |", "|---|---:|---:|"]
        L += [f"| `{s['file']}` | {s['bytes']:,} | {s['ms']:.1f} |" for s in n["corpora"]["combined"]["slowest"]]
        L.append("")

    if "wasm" in g:
        w = g["wasm"]
        d = w["has_error_disagreements"]
        L += ["## WASM throughput (web-tree-sitter under Node, single-threaded)", "",
              f"`tree-sitter-al.wasm` ({w['wasm_bytes']:,} bytes, checked fresh with "
              f"`tools/check-wasm-fresh.sh`), web-tree-sitter {w['web_tree_sitter']}. Same file list, "
              f"read first ({w['read_seconds']:.2f} s); each file is decoded to a JS string outside "
              f"the timed region (a UTF-8 BOM kept; UTF-16 decoded as UTF-16, as natively), so only `parser.parse()` is timed. Warm-up discarded, "
              f"{w['repeats']} timed passes.", "",
              "| corpus | files | has_error | files/s | MiB/s | p50 ms | p95 ms | p99 ms | max ms |",
              "|---|---:|---:|---:|---:|---:|---:|---:|---:|"]
        for name, c in w["corpora"].items():
            lt = c["latency_ms"]
            L.append(f"| {name} | {c['files']:,} | {c['has_error']} | {_t(c['single']['files_per_s'], '{:,.0f}')} | "
                     f"{_t(c['single']['mib_per_s'], '{:.2f}')} | {lt['p50']:.2f} | {lt['p95']:.2f} | "
                     f"{lt['p99']:.2f} | {lt['max']:.1f} |")
        L += ["", f"**has_error agreement with native, per file:** "
              + ("every file agrees." if not (d["wasm_only"] or d["native_only"]) else
                 f"{len(d['wasm_only'])} files error only in WASM, {len(d['native_only'])} only natively "
                 "-- a finding, listed in the JSON."),
              f"Files that are not valid UTF-8 (decoded with U+FFFD replacement in WASM only): "
              f"{len(w['invalid_utf8_files'])}.", ""]
        if "native" in g:
            nat, was = g["native"]["corpora"]["combined"], w["corpora"]["combined"]
            ratio = was['single']['seconds']['median'] / nat['single']['seconds']['median']
            L += [f"WASM / native single-threaded time, all corpora: {ratio:.2f}x"
                  + (" -- WASM is the faster one here; see the caveat on the native build." if ratio < 1 else ".")
                  , ""]

    if "incremental" in g:
        i = g["incremental"]
        L += ["## Fresh against incremental equivalence", "",
              f"Seed `{i['seed']}`, {i['sample_size']} files ({', '.join(f'{k} {v}' for k, v in i['categories'].items())}; "
              f"{i['files_with_if']} with `#if`, {i['bom_files']} with a BOM, {i['crlf_files']} with CRLF). "
              "Each file gets every applicable edit kind once from the original tree (*independent*), then "
              "the same kinds again one after another, each reusing the previous incremental tree (*chain*). "
              "Per edit: `Tree.edit()` with byte offsets and points, `parse(new, old)`, `parse(new)`, and the "
              "complete cursor-derived trees compared: every node (named and anonymous), type, named/"
              "missing/extra, field name, byte and point spans, and `has_error`.", "",
              f"- edits checked: **{i['edits_checked']:,}**; mismatches: **{i['mismatches']}**",
              "- independent edits per kind: " + ", ".join(f"{k} {v}" for k, v in i["edits_per_kind_independent"].items()),
              f"- incremental parse, ms: p50 {i['incremental_ms']['p50']:.2f}, p95 {i['incremental_ms']['p95']:.2f}, "
              f"max {i['incremental_ms']['max']:.1f}",
              f"- fresh parse of the same text, ms: p50 {i['fresh_ms']['p50']:.2f}, p95 {i['fresh_ms']['p95']:.2f}, "
              f"max {i['fresh_ms']['max']:.1f}",
              f"- incremental / fresh time per edit: median **{i['speed_ratio_incremental_over_fresh']['median']:.3f}**, "
              f"p95 {i['speed_ratio_incremental_over_fresh']['p95']:.3f}", ""]
        if i["mismatches"]:
            L += ["Mismatches (see docs/deferred-work.md):", "",
                  *(f"- `{m['file']}` {m['mode']} {m['kind']} at byte {m['start']}" for m in i["mismatch_details"]), ""]

    if "build" in g:
        b = g["build"]
        L += ["## Build and size", "",
              "| | |", "|---|---|",
              f"| `tree-sitter generate`, s | {_t(b['generate'])} (warm-up discarded, median of 3) |",
              f"| native build, s (`{b['build_command']}`) | {_t(b['build'])} (median of 3) |",
              f"| `generate` left src/ byte-identical | {'yes' if b['src_unchanged_by_generate'] else 'NO: ' + b['git_diff_stat_src']} |",
              f"| src/parser.c | {b['parser_c_mib']} MiB ({b['parser_c_bytes']:,} bytes) |",
              f"| STATE_COUNT / LARGE_STATE_COUNT / SYMBOL_COUNT | {b['STATE_COUNT']:,} / {b['LARGE_STATE_COUNT']:,} / {b['SYMBOL_COUNT']:,} |",
              f"| LANGUAGE_VERSION (ABI) | {b['LANGUAGE_VERSION']} |",
              f"| tree-sitter-al.wasm | {b['wasm_bytes']:,} bytes ({_mib(b['wasm_bytes'])}) |", ""]

    if "oracle" in g:
        o = g["oracle"]
        q = o["quick"]
        L += ["## Config oracle", "",
              "Wall time and memory of the whole process tree (ts-lock's bash, the oracle, and all "
              f"{o['workers']} workers), sampled every 250 ms. *Aggregate* is the peak of the SUM of RSS "
              "(Windows: working set) over the tree; *per-process max* is the largest single process, "
              "which is what the oracle's own `peak RSS (max over processes)` line reports. *Private sum* "
              "is the peak sum of private (committed) bytes: it never counts a shared page twice, but it "
              "counts memory committed and not resident, so it can exceed the RSS sum.", "",
              "| tier | runs | wall, s | aggregate peak | per-process max | private sum |", "|---|---:|---:|---:|---:|---:|",
              f"| quick | {q['repeats']} (+1 warm-up) | {_t(q['seconds'])} | {_mib(q['peak_rss_sum_bytes'])} | "
              f"{_mib(q['peak_rss_single_process_bytes'])} | {_mib(q['peak_private_sum_bytes'])} |"]
        if "full" in o:
            f = o["full"]
            L += [f"| full, 4 corpora | 1 (no warm-up) | {f['seconds']:.0f} | {_mib(f['peak_rss_sum_bytes'])} | "
                  f"{_mib(f['peak_rss_single_process_bytes'])} | {_mib(f['peak_private_sum_bytes'])} |", "",
                  f"Full tier exit code {f['exit_code']}, {f['samples']} samples, up to {f['peak_processes']} "
                  f"processes. The oracle's own line for the same run: `{f['oracle_own_peak_rss_line']}`."]
        L.append("")

    L += CAVEATS
    return "\n".join(L) + "\n"


CAVEATS = """## Reproducing and comparing

```bash
python -m tools.perf baseline                       # everything, all 4 corpora (~30 min); writes
                                                    # docs/perf/baseline-<date>.json and this file
python -m tools.perf native      [--corpus LABEL ...] [--out DIR]   # one group at a time; the
python -m tools.perf wasm        [--corpus LABEL ...] [--out DIR]   # result goes to
python -m tools.perf incremental [--corpus LABEL ...] [--out DIR]   # tools/perf/reports/ unless
python -m tools.perf build                                          # --out says otherwise
python -m tools.perf oracle      [--no-full]
python -m tools.perf compare OLD.json NEW.json      # per-metric delta and relative change
python -m tools.perf render docs/perf/baseline-<date>.json          # re-render this file
```

Corpus labels are the oracle's (`tools/config_oracle/__main__.CORPORA`): `bc-history`, `dc`,
`bc28.1` (`AL_BC28_ROOT`), `bcapps-29.0` (`AL_BCAPPS29_ROOT`). `incremental` exits 1 on any
mismatch; the others exit 0 when they complete.

`compare` flags `!` when a median moved by more than the measured spread (max - min) of either
run, and `?` when a value with no measured spread changed (a single measurement, a derived
percentile, a count). It sets no pass/fail thresholds: those are roadmap D2's. A sub-command's
result holds only its own group, and `compare` lists the other file's extra metrics as `-`/`+`.

## What the numbers mean, and caveats

- **Timing** is `time.perf_counter_ns` (Node: `process.hrtime.bigint`). A warm-up pass is
  discarded, then 3 passes; figures are the median and (min-max). Only the parse call is timed.
  Reading the files is timed on its own and depends on the OS file cache (the first run after
  a reboot reads from disk).
- **Percentiles** are linear interpolation between closest ranks (numpy's default), over each
  file's median time across the passes. p99 over ~70k files is well sampled; `max` is one file.
- **Parallel** throughput is bounded by the slowest chunk at the end of the pass and by the
  machine's other load; it is the number to compare between runs on the same machine, not a
  scaling law.
- **Machine load** is recorded at the start (and end) of every run; above 20% CPU the run
  warns in its output and in the JSON. This workstation runs other work, so the spread is the
  honest error bar: compare medians only when the spreads are small against the delta.
- **Memory**: RSS sums count shared pages (the parser DLL mapped by every worker) once per
  process, so the aggregate over-states physical use. The private sum (Windows only) counts
  no shared page twice but is commit charge, not residency, so it can be the larger. Both are
  sampled, so a peak shorter than 250 ms can be missed.
- **Incremental equivalence** covers only the edit kinds listed, at one pseudo-random site per
  kind per file; it proves nothing about other edits. The seed is fixed so a later run edits
  the same sites while the corpora and the parser are unchanged.
- **The native library is `tree-sitter build`'s**, which on this machine compiles with MSVC
  (`al.dll` imports `VCRUNTIME140.dll`); the WASM is built by emscripten (clang). That native
  is slower than WASM single-threaded is a measured fact about these two builds, not about the
  grammar. Compare native with native and WASM with WASM; a different compiler or flags moves
  the native numbers without any grammar change.
- `benchmark.sh` (`tree-sitter parse` over BC.History, appending to the untracked
  `benchmark-results.txt`) measures CLI wall time including process start and I/O; it is kept,
  and is not comparable with these numbers.
""".splitlines()
